LeagueManager/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueManager.Models;
using Microsoft.AspNet.Identity;


namespace LeagueManager.Controllers
{
    // This secion all needs the user to be logged on as an Administrator
    [Authorize(Roles = "Admin")]
    public class AdministratorController : Controller
    {
        private LeagueManagerDB db = new LeagueManagerDB();

        // GET: Adminstrator
        // Displays the leagues belonging to the current user.
        public ActionResult Index()
        {
            return View(db.Leagues.ToList());
        }

        // GET: Adminstrator/LeagueDetails/5
        // Displays the details of the selected league.
        public ActionResult LeagueDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }
            return View(league);
        }

        // GET: Adminstrator/CreateLeague
        // Set up for creating a new league.
        public ActionResult CreateLeague()
        {
            // now build the view model
            CreateEditLeagueViewModel createleague = new CreateEditLeagueViewModel(db, null, User.Identity.GetUserName());

            // pass the view model to the view
            return View(createleague);
        }

        // POST: Adminstrator/CreateLeague
        // Recieve the details for creating a new league and save it to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLeague(CreateEditLeagueViewModel createleague)
        {
            if (ModelState.IsValid)
            {
                League league = new League();
                createleague.Initalise(league, User.Identity.GetUserName());

                //Add sides to league Members.
                foreach (int item in createleague.SelectedSides)
                {
                    Side s = db.Sides.Find(item);
                    league.Members.Add(s);
                }
                db.Leagues.Add(league);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(createleague);
        }

        // GET: Adminstrator/EditLeague/5
        // Display the details of a league to edit.
        public ActionResult EditLeague(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            // now build the view model
            CreateEditLeagueViewModel editleague = new CreateEditLeagueViewModel(db, id, User.Identity.GetUserName());

            // pass the view model to the view
            return View(editleague);
        }

        // POST: Adminstrator/EditLeague/5
        // Recieve the new details and save them to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditLeague(CreateEditLeagueViewModel editleague)
        {
            if (ModelState.IsValid)
            {
                League league = db.Leagues.Find(editleague.League.Id);
                //Initalize our league with the data collected from our edit form, but keep OwnerName the same.
                editleague.Initalise(league, editleague.League.OwnerName);
                db.Entry(league).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(editleague);
        }

        // GET: Adminstrator/EditLeagueMembers/5
        // Editing which sides are members of the league.
        public ActionResult EditLeagueMembers(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            //Initialise our view model
            EditLeagueMembersViewModel viewModel = new EditLeagueMembersViewModel(league, db, league.OwnerName);

            return View(viewModel);
        }

        // Called from EditLeagueMembers, we add the side then reload EditLeagueMembers.
        public ActionResult AddSideToLeague(int LeagueId, int SideId)
        {
            // Find the League and  the Side.
            League league = db.Leagues.Find(LeagueId);
            Side side = db.Sides.Find(SideId);

            // Add the Side to the League and save to the database.
            league.Members.Add(side);
            db.Entry(league).State = EntityState.Modified;
            db.SaveChanges();

            // Go back to Editing the League Members.
            return RedirectToAction("EditLeagueMembers", new { id = LeagueId });
        }

        // Called from EditLeagueMembers, we remove the side, delete associated matches and then reload EditLeagueMembers.
        public ActionResult RemoveSideFromLeague(int LeagueId, int SideId)
        {
            // Find the League and  the Side.
            League league = db.Leagues.Find(LeagueId);
            Side side = db.Sides.Find(SideId);

            // Remove the Side to the League and save to the database.
            league.Members.Remove(side);
            db.Entry(league).State = EntityState.Modified;

            // Find the Matches in the League that the Side is a part of.
            List<Match> matchesForSideInLeague = db.Matches.Where(m => m.LeagueId == LeagueId &&
                                                                    (m.Side1Id == SideId || m.Side2Id == SideId))
                                                        .ToList();

            // Delete all of the Matches and Save to the Database.
            foreach(Match match in matchesForSideInLeague)
            {
                db.Matches.Remove(match);
            }
            db.SaveChanges();

            return RedirectToAction("EditLeagueMembers", new { id = LeagueId });
        }

        // GET: Adminstrator/AddNewSideToLeague/5
        // Create a new side and add it to the specified League.
        public ActionResult AddNewSideToLeague(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            //Initialise our view model
            CreateEditSideViewModel viewModel = new CreateEditSideViewModel(db, null, league.OwnerName, id);

            return View(viewModel);
        }

        // POST: Adminstrator/AddNewSideToLeague/5
        // Recieve the details for creating a new side and save it to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewSideToLeague(CreateEditSideViewModel createside)
        {
            if (ModelState.IsValid)
            {
                //Create the new side and initialise it.
                Side side = new Side();
                createside.Initalise(side);
                //Find the League we want to to put the side in and add it.
                League l = db.Leagues.Find(createside.IdOfLeagueToAddTo);
                side.LeaguesIn.Add(l);
                // Add the side to the database and save.
                db.Sides.Add(side);
                db.SaveChanges();
                //Go back to the League view/
                return RedirectToAction("Index");
            }

            return View(createside);
        }


        // GET: Adminstrator/DeleteLeague/5
        // Show the details of the league to confirm the delete.
        public ActionResult DeleteLeague(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            League league = db.Leagues.Find(id);

            if (league == null)
            {
                return HttpNotFound();
            }

            // Find out how many Matches are in the League and tell the View.
            List<Match> sidematches = db.Matches.Where(m => m.Side1Id == id || m.Side2Id == id)
                                    .ToList();
            ViewBag.noOfMatches = sidematches.Count;

            return View(league);
        }

        // POST: Adminstrator/DeleteLeague/5
        // Delete this league from the database, this will delete all the Matches as well.
        [HttpPost, ActionName("DeleteLeague")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            League league = db.Leagues.Find(id);
            db.Leagues.Remove(league);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Adminstrator/ViewLeagueTable/5
        // Show the league table for the selected league.
        public ActionResult ViewLeagueTable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            LeagueResults results = new LeagueResults(db, (int)id);

            return View(results);
        }

        // GET: Adminstrator/ViewSides
        // View all the sides.
        public ActionResult ViewSides()
        {
            return View(db.Sides.ToList());
        }

        // GET: Adminstrator/SideDetails/5
        // Show the details for the selected side.
        public ActionResult SideDetails(int? id)

LeagueManager/Views/Administrator/ConfirmSideAndMatchesDelete.cshtml
@model LeagueManager.Models.Side

@{
    ViewBag.Title = "ConfirmSideAndMatchesDelete";
}

<h2>Confirm Delete of @Model.Name</h2>

@Html.HiddenFor(model => model.Id)

<div>
    <p>
        This Side has @ViewBag.noOfMatches matches associated with it. 
        They will be deleted too. Please confirm that you wish to continue.
    </p>

    @using (Html.BeginForm("ConfirmSideAndMatchesDelete", "Administrator", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirm" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewSides")
        </div>
    }
</div>

LeagueManager/Views/Administrator/CreateLeague.cshtml
@model LeagueManager.Models.CreateEditLeagueViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @{Html.RenderPartial("~/Views/Shared/_CreateLeague.cshtml", Model); }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueManager/Views/Administrator/CreateMatch.cshtml
@model LeagueManager.Models.CreateEditMatchViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @{ Html.RenderPartial("~/Views/Shared/_CreateEditMatch.cshtml", Model);}

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewLeagueMatches", new { id = Model.IdOfLeagueMatchIsIn })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueManager/Views/Administrator/CreateSide.cshtml
@model LeagueManager.Models.CreateEditSideViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @{ Html.RenderPartial("~/Views/Shared/_CreateSide.cshtml", Model);}

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewSides")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueManager/Views/Administrator/DeleteLeague.cshtml
@model LeagueManager.Models.League

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

@if (ViewBag.noOfMatches == 1)
{
    <p>
        Warning deleting this League will also delete the match in the League.
    </p>
}

@if (ViewBag.noOfMatches > 1)
{
    <p>
        Warning deleting this League will also delete the @ViewBag.noOfMatches matches in the League.
    </p>
}

<div>

    @{Html.RenderPartial("~/Views/Shared/_LeagueDetails.cshtml", Model); }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LeagueManager/Views/Administrator/DeleteSide.cshtml
@model LeagueManager.Models.Side

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div>

    @{Html.RenderPartial("~/Views/Shared/_SideDetails.cshtml", Model); }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="DeleteSide" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewSides")
        </div>
    }
</div>

LeagueManager/Views/Administrator/EditLeague.cshtml
@model LeagueManager.Models.CreateEditLeagueViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @{Html.RenderPartial("~/Views/Shared/_EditLeague.cshtml", Model); }

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueManager/Views/Administrator/EditLeagueMembers.cshtml
@model LeagueManager.Models.EditLeagueMembersViewModel

@{
    ViewBag.Title = "EditLeagueMembers";
}

<h2>Edit Members of @Model.League.Name</h2>


<table class="table">
    <tr>
        <th>
            @Html.Label("Team Name")
        </th>
        <th>
            <!-- Column for Add Button -->
        </th>
        <th>
            <!-- Column for Remove Button -->
        </th>
        <th>
            <!-- Column for Warning message -->
        </th>
    </tr>

    @foreach (LeagueManager.Models.SideMatchLeagueInfo smi in Model.SideInfo)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => smi.Side.Name)
            </td>
            <td>
                @if(smi.IsInLeague == false)
                {
                    @Html.ActionLink("Add", "AddSideToLeague", new { LeagueId = smi.LeagueId, SideId = smi.Side.Id }, new { @class="btn btn-default" })
                }
            </td>
            <td>
                @if(smi.IsInLeague == true)
                {
                    @Html.ActionLink("Remove", "RemoveSideFromLeague", new { LeagueId = smi.LeagueId, SideId = smi.Side.Id }, new { @class = "btn btn-default" })
                }
            </td>
            <td>
                @if(smi.IsInLeague == true)
                {
                    if(smi.noOfMatches == 1)
                    {
                        <p>
                            Removing this Team will delete 1 match.
                        </p>
                    }
                    if(smi.noOfMatches > 1)
                    {
                        <p>
                            Removing this Team will delete @smi.noOfMatches.ToString() matches.
                        </p>
                    }
                }
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to League Edit", "EditLeague", new { id = Model.League.Id})
</div>

LeagueManager/Views/Administrator/EditSide.cshtml
@model LeagueManager.Models.Side

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @{ Html.RenderPartial("~/Views/Shared/_EditSide.cshtml", Model);}

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewSides")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueManager/Views/Administrator/LeagueDetails.cshtml
@model LeagueManager.Models.League

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@{Html.RenderPartial("~/Views/Shared/_LeagueDetails.cshtml", Model); }

<p>
    @Html.ActionLink("Edit", "EditLeague", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeagueManager/Views/Administrator/SideDetails.cshtml
@model LeagueManager.Models.Side

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@{Html.RenderPartial("~/Views/Shared/_SideDetails.cshtml", Model); }

<p>
    @Html.ActionLink("Edit", "EditSide", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "ViewSides")
</p>

LeagueManager/Views/Administrator/ViewLeagueMatches.cshtml
@model LeagueManager.Models.ListLeagueMatchesViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Matches in @Model.LeagueName</h2>

<p>
    @Html.ActionLink("Create New Match", "CreateMatch", new { id = Model.LeagueId })
</p>

@{Html.RenderPartial("~/Views/Shared/_ViewLeagueMatches.cshtml", Model.ListOfMatches); }

<div>
    @Html.ActionLink("Back to Leagues", "Index")
</div>

LeagueManager/Views/Administrator/ViewLeagueTable.cshtml
@model LeagueManager.Models.LeagueResults

@{
    ViewBag.Title = "View League";
}

@{Html.RenderPartial("~/Views/Shared/_ViewLeagueTable.cshtml", Model); }

<div>
    @Html.ActionLink("Back to Leagues", "Index")
</div>

LeagueManager/Views/Administrator/ViewSides.cshtml
@model IEnumerable<LeagueManager.Models.Side>

@{
    ViewBag.Title = "My Sides";
}

<h2>All Sides</h2>


@{ Html.RenderPartial("~/Views/Shared/_ViewSides.cshtml", Model);}


<div>
    @Html.ActionLink("Back to Leagues", "Index")
</div>