LeagueManager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using LeagueManager.Models;

namespace LeagueManager.Controllers
{
    public class HomeController : Controller
    {
        private LeagueManagerDB db = new LeagueManagerDB();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Guide()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "For any enquiries contact:";

            return View();
        }

        [Authorize (Roles = "Admin")]
        public ActionResult Administrator()
        {
            return View();
        }

    }
}

LeagueManager/Controllers/MyLeaguesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueManager.Models;
using Microsoft.AspNet.Identity;


namespace LeagueManager.Controllers
{
    // This secion all needs the user to be logged on.
    [Authorize]
    public class MyLeaguesController : Controller
    {
        private LeagueManagerDB db = new LeagueManagerDB();

        // GET: MyLeagues
        // Displays the leagues belonging to the current user.
        public ActionResult Index()
        {
            string userName = User.Identity.GetUserName();

            return View(db.Leagues.Where(l => l.OwnerName == userName)
                                  .ToList());
        }

        // GET: MyLeagues/LeagueDetails/5
        // Displays the details of the selected league.
        public ActionResult LeagueDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            League league = db.Leagues.Find(id);

            if (league == null)
            {
                return HttpNotFound();
            }

            // Make sure it is the Owners user.
            if(league.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            return View(league);
        }

        // GET: MyLeagues/CreateLeague
        // Set up for creating a new league.
        public ActionResult CreateLeague()
        {
            // now build the view model
            CreateEditLeagueViewModel createleague = new CreateEditLeagueViewModel(db, null, User.Identity.GetUserName());

            // pass the view model to the view
            return View(createleague);
        }

        // POST: MyLeagues/CreateLeague
        // Recieve the details for creating a new league and save it to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLeague(CreateEditLeagueViewModel createleague)
        {
            if (ModelState.IsValid)
            {
                League league = new League();
                createleague.Initalise(league, User.Identity.GetUserName());

                //Add sides to league Members.
                foreach (int item in createleague.SelectedSides)
                {
                    Side s = db.Sides.Find(item);
                    league.Members.Add(s);
                }
                db.Leagues.Add(league);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(createleague);
        }

        // GET: MyLeagues/EditLeague/5
        // Display the details of a league to edit.
        public ActionResult EditLeague(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            // Make sure it is the Owners user.
            if (league.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            // now build the view model
            CreateEditLeagueViewModel editleague = new CreateEditLeagueViewModel(db, id, User.Identity.GetUserName());

            // pass the view model to the view
            return View(editleague);
        }

        // POST: MyLeagues/EditLeague/5
        // Recieve the new details and save them to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditLeague(CreateEditLeagueViewModel editleague)
        {
            if (ModelState.IsValid)
            {
                League league = db.Leagues.Find(editleague.League.Id);
                // Make sure it is the Owners user.
                if (league.OwnerName != User.Identity.GetUserName())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
                }
                //Initalize our league with the data collected from our edit form.
                editleague.Initalise(league, User.Identity.GetUserName());
                db.Entry(league).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(editleague);
        }

        // GET: MyLeagues/EditLeagueMembers/5
        // Editing which sides are members of the league.
        public ActionResult EditLeagueMembers(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            // Make sure it is the Owners user.
            if (league.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            //Initialise our view model
            EditLeagueMembersViewModel viewModel = new EditLeagueMembersViewModel(league, db, User.Identity.GetUserName());

            return View(viewModel);
        }

        // Called from EditLeagueMembers, we add the side then reload EditLeagueMembers.
        public ActionResult AddSideToLeague(int LeagueId, int SideId)
        {
            // Find the League and  the Side.
            League league = db.Leagues.Find(LeagueId);
            Side side = db.Sides.Find(SideId);

            // Make sure it is the Owners user.
            if (league.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            if (side.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            // Add the Side to the League and save to the database.
            league.Members.Add(side);
            db.Entry(league).State = EntityState.Modified;
            db.SaveChanges();

            // Go back to Editing the League Members.
            return RedirectToAction("EditLeagueMembers", new { id = LeagueId });
        }

        // Called from EditLeagueMembers, we remove the side, delete associated matches and then reload EditLeagueMembers.
        public ActionResult RemoveSideFromLeague(int LeagueId, int SideId)
        {
            // Find the League and  the Side.
            League league = db.Leagues.Find(LeagueId);
            Side side = db.Sides.Find(SideId);

            // Make sure it is the Owners user.
            if (league.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            if (side.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            // Remove the Side to the League and save to the database.
            league.Members.Remove(side);
            db.Entry(league).State = EntityState.Modified;

            // Find the Matches in the League that the Side is a part of.
            List<Match> matchesForSideInLeague = db.Matches.Where(m => m.LeagueId == LeagueId &&
                                                                    (m.Side1Id == SideId || m.Side2Id == SideId))
                                                        .ToList();

            // Delete all of the Matches and Save to the Database.
            foreach (Match match in matchesForSideInLeague)
            {
                db.Matches.Remove(match);
            }
            db.SaveChanges();

            return RedirectToAction("EditLeagueMembers", new { id = LeagueId });
        }

        // GET: MyLeagues/AddNewSideToLeague/5
        // Create a new side and add it to the specified League.
        public ActionResult AddNewSideToLeague(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }

            // Make sure it is the Owners user.
            if (league.OwnerName != User.Identity.GetUserName())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            //Initialise our view model
            CreateEditSideViewModel viewModel = new CreateEditSideViewModel(db, null, User.Identity.GetUserName(), id);

            return View(viewModel);
        }

        // POST: MyLeagues/AddNewSideToLeague/5
        // Recieve the details for creating a new side and save it to the database.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewSideToLeague(CreateEditSideViewModel createside)
        {
            if (ModelState.IsValid)
            {
                //Create the new side and initialise it.
                Side side = new Side();
                createside.Initalise(side);
                //Find the League we want to to put the side in and add it.
                League league = db.Leagues.Find(createside.IdOfLeagueToAddTo);
                // Make sure it is the Owners user.
                if (league.OwnerName != User.Identity.GetUserName())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
                }
                side.LeaguesIn.Add(league);

LeagueManager/Controllers/PublicLeaguesController.cs
using LeagueManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LeagueManager.Controllers
{
    public class PublicLeaguesController : Controller
    {
        private LeagueManagerDB db = new LeagueManagerDB();

        // GET: PublicLeagues
        public ActionResult Index()
        {
            return View(db.Leagues.Where(l => l.Public == true).ToList());
        }

        public ActionResult ViewLeagueTable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            LeagueResults results = new LeagueResults(db, (int)id);

            return View(results);
        }
    }
}

LeagueManager/Views/Home/About.cshtml
@{
    ViewBag.Title = "Welcome to League Manager.";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    League Manager is a project that I started to help me learn asp.net. <br />
    The project is an MVC 5 Web Application using the 4.5.2 .NET Framework. <br />
    It is using Individual User Accounts. <br />
    It is built using a code first approach with the Entity Framework. <br />
    Created the Side class with scaffolded Create, Details, Edit and Delete Views.<br />
    Created the League class with scaffolded Create, Details, Edit and Delete Views.<br />
    Created the Match class with scaffolded Create, Details, Edit and Delete Views.<br />
    Added data Annotations to League scaffolded Side. <br />
    Added foreign keys for the Match class with fluent api. <br />
    Merged all the create, details, edit and delete for the three classes into Administrator controller. <br />
    Added UserName to register and logon. <br />
    Created View Models for League, Side and Match to create the data for list boxes. <br />
    Added confirmation to deleting Sides if they have matches associated with them. <br />
    Added Test data to DbInitialiser. <br />
    Put much of what could be reused in the views into partial views. <br />
    Tidied up appearance of views. <br />
    Changed the way League editing was done so that Sides are added/removed on a separate page to enable deleting associated matches. <br />
    Created SideResults and LeagueResults to generate the data needed for a League Table, added League Table View. <br />
    Created a copy of the Administration controller called MyLeagues (with Views). <br />
    Added showing of Owner Name if user is Administrator. <br />
    Created an Admin user with an Admin Role. <br />
    Added Authorisation to Administrator and MyLeagues controllers. <br />
    Changed MyLeagues controller so it could only access the current users data. <br />
    Added Premiership data to DbInitialiser. <br />
    Added Public Leagues controller to display Leagues that are public. <br />
    Tidied up front page and navigation. <br />
    Added Demo User data and created a guide to using the site. <br />

</p>


<p>
    Future Updates will include:
</p>

<p>
    Add Date played to Match. <br />
    Add editing Users to Administrator. <br />
    Add forgotten Password Functionality. <br />
    Add Sign on from External Providers. <br />
    Add bonus points option to League and Match. <br />
    Allow more than two sides to be included in a match, need new side/match/result class. <br />
    Add types of League to speed up creation. <br />
    Improve the way Editing League Members accesses the database. <br />
</p>

LeagueManager/Views/Home/Administrator.cshtml
@{
    ViewBag.Title = "Administrator";
}
<h2>@ViewBag.Title.</h2>

<h3>Links for Administrator Functions</h3>

<p>
    @Html.ActionLink("League Administration", "Index", "LeagueAdministrator")
</p>

<p>
    @Html.ActionLink("Side Administration", "Index", "SideAdministrator")
</p>

<p>
    @Html.ActionLink("Match Administration", "Index", "MatchAdministrator")
</p>

LeagueManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>



<p>
    <strong>Iain Bowler:</strong>   <a href="mailto:leaguemanager@jokedb.net">leaguemanager@jokedb.net</a><br />
</p>

LeagueManager/Views/Home/Guide.cshtml
@{
    ViewBag.Title = "Guide";
}

<h2>Guide</h2>

<p>
    League Manager is a website that enables you to create and maintain your own football leagues.
</p>

<h4>Step 1</h4>

<p>
    The first step is to register with the Website, so that we know which Leagues belong to you.
    You can do that @Html.ActionLink("here", "Register", "Account")
</p>

<img src="@Url.Content("~/Content/Images/Register.png")"  width="657" height="326" />

<h4>Step 2</h4>

<p>
    Now you are ready to create you own Leagues. This is done in the MyLeagues section of the website.
    There is a link to this section in the Navigation Bar at the top of every page.
</p>

<img src="@Url.Content("~/Content/Images/MyLeagues.png")" width="649" height="340" />

<h4>Step 3</h4>

<p>
    To create a New League click on the "Create New League" link towards the top left of the page.
</p>

<img src="@Url.Content("~/Content/Images/CreateNewLeague1.png")" width="659" height="221" />
<img src="@Url.Content("~/Content/Images/CreateNewLeague2.png")" width="648" height="389" />

<h4>Step 4</h4>

<p>
    It's now time to add some teams to you League. The easiest way to do that is to Click on the Add
    New Team option at the right hand side of the row that summarises your League.
</p>

<img src="@Url.Content("~/Content/Images/AddTeam1.png")" width="658" height="260" />
<img src="@Url.Content("~/Content/Images/AddTeam2.png")" width="657" height="241" />

<h4>Step 5</h4>

<p>
    Once you have added your teams to your league you can now add matches between the teams. There is an
    Add Match option next to the Add Team option on the right hand side of your League's summary.
</p>

<img src="@Url.Content("~/Content/Images/AddMatch1.png")" width="658" height="292" />
<img src="@Url.Content("~/Content/Images/AddMatch2.png")" width="657" height="340" />

<h4>Step 6</h4>

<p>
    Congratulations, now your League table is ready to view and you can do this by clicking on the name of your League.
</p>

<img src="@Url.Content("~/Content/Images/ShowLeagueTable1.png")" width="658" height="288" />
<img src="@Url.Content("~/Content/Images/ShowLeagueTable2.png")" width="658" height="289" />

LeagueManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>League Manager</h1>
    <p class="lead">Welcome to League Manager. <br>
    Here you can create and manage your own Football League.
    </p>
    <p>@Html.ActionLink("Learn More", "Guide", "Home", new { @class="btn btn-primary btn-lg" })</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Create your own League.</h2>
        @if (User.Identity.IsAuthenticated != true)
        {
            <p>
                If you want to create and manage your own league first you will need to create an account:
            </p>
            <p>
                @Html.ActionLink("Create an New Account", "Register", "Account")
            </p>
            <p>
                Or login to an existing account:
            </p>
            <p>
                @Html.ActionLink("Login", "Login", "Account")
            </p>
        }
        else
        {
            <p>
                Now you are Logged In you're ready to create a new league:
            </p>
            <p>
                @Html.ActionLink("Create a new League", "CreateLeague", "MyLeagues")
            </p>
            <p>
                Or manage your existing Leagues:
            </p>
            <p>
                @Html.ActionLink("My Leagues", "Index", "MyLeagues")
            </p>
        }
    </div>
    <div class="col-md-4">
        <h2>View Public Leagues</h2>
        <p>
            When you create your own League you have the option to make your league Public so everyone can view it.
        </p>
        <p>
            Here you can see the Public leagues that have been created so far:
        </p>
        <p>
            @Html.ActionLink("View Public Leagues", "Index", "PublicLeagues")
        </p>
    </div>
</div>

LeagueManager/Views/Home/ViewLeague.cshtml
@model LeagueManager.Models.LeagueResults

@{
    ViewBag.Title = "View League";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Testing Displaying a League.</p>

<table class="table">
    <tr>
        <th>
            @Html.Label("Side Title", "Team Name")
        </th>
        <th>
            @Html.Label("Played Title", "Games Played")
        </th>
        <th>
            @Html.Label("Won Title", "Games Won")
        </th>
        <th>
            @Html.Label("Drawn Title", "Games Drawn")
        </th>
        <th>
            @Html.Label("Lost Title", "Games Lost")
        </th>
        <th>
            @Html.Label("For Title", "Goals For")
        </th>
        <th>
            @Html.Label("Against Title", "Goals Against")
        </th>
        <th>
            @Html.Label("Difference Title", "Goal Difference")
        </th>
        <th>
            @Html.Label("Points Title", "Points")
        </th>

    </tr>

    @foreach (LeagueManager.Models.SideResults item in Model.Results)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SideName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchesPlayed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchesWon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchesDrawn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchesLost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalScoreFor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalScoreAgainst)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalScoreDifference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Points)
            </td>
        </tr>
    }

</table>